version: '3'
services:
  web:
    build: .
    container_name: "signnow-web"
    ports:
     - "13000:3000"
    environment:
     - MONGO_ENABLE=true
     - MONGO_HOST=signnow-mongodb
     - MONGO_PORT=27017
     - MONGO_DB_NAME=mydb
     - APP_PORT=3000
    depends_on:
     - mongodb

  mongodb:
    image: mongo:3.2.20-jessie
    container_name: "signnow-mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
    volumes:
      - db-data:/data/db
    # local access for debug
    ports:
      - 27017:27017

volumes:
  db-data: